name: Java CICD with Maven

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    # [{name: "blah", uses: "some action", with: {}}]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_app_name: ${{secrets.APP_NAME}}
          heroku_email: ${{secrets.APP_EMAIL}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
